### ISSUE TITLE
Does FIFE support prediction with future features?

### ISSUE THREAD

**Issue by goleng** [IDA-HumanCapital/fife#81]
I started playing with this package recently and I like it a lot. However, I'm not sure I fully understand the predict/forecast methods/functions. In particular, prediction or forecasts with some future features states (assuming we have dynamic features) for which we know their future values. 

Example: In the REIGN dataset used in the example notebook, some of the continuous features are changing with time for a given leader. Assuming I trained a model with these features but was more interested in what the survival probability of a leader would be if the value of column say, "**irregular**" is of some value.

Is this sort of predictions/forecasts possible with FIFE? Or better, how can one incorporate such into the workflow. 

Please pardon my ignorance. My understand of TTE analysis is somewhat scanty. 

Thanks.

**Comment by jamesmckownbishop** [comment]
Hello, and thank you for your question. I'm glad you like FIFE!

Yes, FIFE supports predictions for whatever feature values you can introduce to your dataset. You can use [the `subset` argument to `predict`](https://github.com/IDA-HumanCapital/fife/blob/377a5e20c4382b7bf02599dd2992f7decefeee71/fife/lgb_modelers.py#L328-L330) to flag the observations in your data (i.e., the modeler.data attribute) for which you want predictions. If you want predictions for an observation that's not in your data, you can either modify an existing observation or append a new one. For example, you could do `modeler.data.loc[len(modeler.data) - 1, "irregular"] = 7.0` to override the value of **irregular** in the last observation with `7.0`.

I expect that you would not want to use the same observation for training and prediction, so it would be fine to override values of prediction observations before instantiating the modeler. One advantage to doing so is that the modeler would automatically apply any modeler-specific transformations ([e.g.](https://github.com/IDA-HumanCapital/fife/blob/377a5e20c4382b7bf02599dd2992f7decefeee71/fife/tf_modelers.py#L475-L484)) to the overriding values.

[`forecast`](https://github.com/IDA-HumanCapital/fife/blob/377a5e20c4382b7bf02599dd2992f7decefeee71/fife/base_modelers.py#L463-L478) is a wrapper for `predict` where the `subset` comprises the observations from the last period in the data. `forecast` also prettifies the raw numpy array of predictions into an id-indexed DataFrame with column headers.

I would be happy to provide more clarification as you would find helpful.

Sincerely,
James

**Comment by goleng** [comment]
@jamesmckownbishop Thanks a lot for the clarifications and additional information on how to make use of the prediction method. I will test it and get back to you if there are still some issues.
